// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestSharpSpecflow.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AdvancedOperationFeature : object, Xunit.IClassFixture<AdvancedOperationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AdvancedOperation.feature"
#line hidden
        
        public AdvancedOperationFeature(AdvancedOperationFeature.FixtureData fixtureData, RestSharpSpecflow_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "AdvancedOperation", "\tAdvanced API testing operations", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify If Product1 Is Always Same")]
        [Xunit.TraitAttribute("FeatureTitle", "AdvancedOperation")]
        [Xunit.TraitAttribute("Description", "Verify If Product1 Is Always Same")]
        [Xunit.TraitAttribute("Category", "smoke")]
        public void VerifyIfProduct1IsAlwaysSame()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify If Product1 Is Always Same", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProductId"});
                table1.AddRow(new string[] {
                            "1"});
#line 6
  testRunner.Given("I perform a GET operation of \"Product/GetProductById/{id}\"", ((string)(null)), table1, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProductId"});
                table2.AddRow(new string[] {
                            "1"});
#line 9
  testRunner.And("I perform another GET operation \"Product/GetProductById/{id}\"", ((string)(null)), table2, "And ");
#line hidden
#line 12
  testRunner.And("I should verify if Product is always the same", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify If Product1 And Product2 Manufacturers Address Are Same")]
        [Xunit.TraitAttribute("FeatureTitle", "AdvancedOperation")]
        [Xunit.TraitAttribute("Description", "Verify If Product1 And Product2 Manufacturers Address Are Same")]
        [Xunit.TraitAttribute("Category", "smoke")]
        public void VerifyIfProduct1AndProduct2ManufacturersAddressAreSame()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify If Product1 And Product2 Manufacturers Address Are Same", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProductId"});
                table3.AddRow(new string[] {
                            "1"});
#line 17
  testRunner.Given("I perform a GET operation of \"Product/GetProductById/{id}\"", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProductId"});
                table4.AddRow(new string[] {
                            "5"});
#line 20
  testRunner.And("I perform another GET operation \"Product/GetProductById/{id}\"", ((string)(null)), table4, "And ");
#line hidden
#line 23
  testRunner.And("I should verify if Product1 and Product2 addresses are the same", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify If Product1 And Product2 Manufacturers Are Same")]
        [Xunit.TraitAttribute("FeatureTitle", "AdvancedOperation")]
        [Xunit.TraitAttribute("Description", "Verify If Product1 And Product2 Manufacturers Are Same")]
        [Xunit.TraitAttribute("Category", "smoke")]
        public void VerifyIfProduct1AndProduct2ManufacturersAreSame()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify If Product1 And Product2 Manufacturers Are Same", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProductId"});
                table5.AddRow(new string[] {
                            "1"});
#line 29
  testRunner.Given("I perform a GET operation of \"Product/GetProductById/{id}\"", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProductId"});
                table6.AddRow(new string[] {
                            "1"});
#line 32
  testRunner.And("I perform another GET operation \"Product/GetProductById/{id}\"", ((string)(null)), table6, "And ");
#line hidden
#line 35
  testRunner.And("I should verify if Product1 and Product2 manufacturers are the same", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AdvancedOperationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AdvancedOperationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
